server {
    listen 80;
    listen [::]:80;
    server_name the-day.yangon-tech-by-okker.site;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name the-day.yangon-tech-by-okker.site;
    server_tokens off;
    ssl_certificate /etc/letsencrypt/live/the-day.yangon-tech-by-okker.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/the-day.yangon-tech-by-okker.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    location / {
        proxy_pass http://127.0.0.1:4217;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
