import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { env } from './config/env.js';
import { router } from './routes/index.js';
import { errorHandler } from './utils/errors.js';
export const app=express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin:env.corsOrigin }));
app.use(express.json({ limit:'16kb' }));
app.use('/api/v1',router);
app.use((req,res) => res.status(404).json({ error:{ message:'Endpoint not found' } }));
app.use(errorHandler);
